name: clash_yaml

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'utils/airport/speedtest/**'
      - 'utils/process_result.py'
      - 'sub/**'
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezone: "Asia/Shanghai"

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Requirements
        run: |
          python3 -m pip install --upgrade pip
          pip install pyyaml requests base64 json

      - name: Prepare directories
        run: |
          mkdir -p ./sub
          mkdir -p ./utils/airport/speedtest

      - name: Download speedtest files
        run: |
          wget -O ./utils/airport/speedtest/lite-linux-amd64.gz https://github.com/xxf098/LiteSpeedTest/releases/download/v0.15.0/lite-linux-amd64-v0.15.0.gz
          gzip -d ./utils/airport/speedtest/lite-linux-amd64.gz
          chmod +x ./utils/airport/speedtest/lite-linux-amd64
          wget -O ./utils/airport/speedtest/lite_config.json https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/utils/airport/speedtest/lite_config_yaml_airport.json

      - name: Run SpeedTest
        run: |
          cd ./utils/airport/speedtest/
          ./lite-linux-amd64 --config ./lite_config.json --test https://raw.githubusercontent.com/mahdibland/SSAggregator/master/sub/airport_merge_yaml.yml > ../../../speedtest.log 2>&1
        continue-on-error: true

      - name: Generate Clash YAML
        run: |
          python3 ./utils/process_result.py
        env:
          TZ: Asia/Shanghai
        if: always()

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update output.py and results'
          file_pattern: 'sub/*.yml output.json speedtest.log'
          branch: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
